hl.on("hyprland.start", function()
    hl.exec_cmd("hyprlock")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("bash -c 'sleep 3 && hyprctl hyprpaper wallpaper \"eDP-1," .. wallpaper .. "\"'")
    hl.exec_cmd("quickshell")
    hl.exec_cmd("[workspace 9 silent] vesktop")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("/usr/lib/kdeconnectd")
    hl.exec_cmd("bash -c 'sleep 2 && hyprpm reload'")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
